FROM python:3.9-buster

RUN python3 -m pip install -U pip
RUN python3 -m pip install -U setuptools
RUN python3 -m pip install -U wheel
RUN python3 -m pip install nvflare

WORKDIR /workspace/

# Copy the requirements.txt file
COPY ./requirements.txt /workspace/requirements.txt

# Install dependencies from requirements.txt
RUN python3 -m pip install -r /workspace/requirements.txt

ENV PYTHONPATH=/workspace/app/code/
ENV NVFLARE_POC_WORKSPACE=/workspace/poc-workspace

CMD ["/bin/bash"]
